### ISSUE TITLE
bug: Not able to quit the application

### ISSUE THREAD

**Issue by jainil-ss** [requestly/requestly#3953]
### Describe your issue?

The application does not close. Tries all the possible ways to close the application, but it does not close.

### Repro steps

1. Open the Requestly app
2. Close the application using the close button, or quit from the system tray or the taskbar.

### What Requestly tool were you using?

- [ ] Extension
- [x] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows

### Requestly Version

v25.11.28

**Comment by wrongsahil** [comment]
@jainil-ss We've addressed this issue before, but I believe there may still be some cases pending. Could you please share a video regarding this?

CC: @nsrCodes

**Comment by jainil-ss** [comment]
@wrongsahil Same issue on the Mac as well

https://github.com/user-attachments/assets/c3686e09-ac76-4318-918c-02753a77b782

**Comment by wrongsahil** [comment]
Hey @jainil-ss. Thanks for the video. Could we schedule a call to gather additional logs for debugging?  
https://calendar.app.google/dDafdAsTotor1EP69

**Comment by Simphiwe-Nhlabati** [comment]
I cannot close mine I even deleted it 
The app still won't close

**Comment by jainil-ss** [comment]
@wrongsahil, It looks like the issue is with the fresh install and first-time run only. After force-closing the application, it started working the next time I tried to close the application. The same thing happened on the Mac as well.

**Comment by Aarushsr12** [comment]
Hey @jainil-ss @Simphiwe-Nhlabati 

Thanks for reporting this issue, we have released a fix for this, can you please try this again!
